Repository Tedeapolis/wet-en-regelgeving, pull requests merged in 2022-01, with the labels that each got.

#238 Nieuwe voertuigen toegevoegd
  docs/offroadvoertuigen.md
Labels: Staff overleg

#230 Verzwaring Artikelen 11 & 25 + Verduidelijking/Toevoeging
  docs/apv.md
Labels: Changes needed

#239 Update opium wet
  docs/wetboek.md
Labels: question

#246 Toevoeging/Verduidelijking Verbod ERP
  docs/apv.md
Labels: Changes needed

#257 Artikel 40 - Winkel en bank overvallen & verwijderen overalregels
  docs/apv.md
  docs/overvallen.md
  mkdocs.yml
Labels: Staff overleg

#252 Update aan Artikel 26 - Belediging
  docs/apv.md
Labels: Staff overleg
